#
# Copyright (c) 2021, RT-Thread Development Team
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#

from building import *
import re

Import('rtconfig')

cwd     = GetCurrentDir()
src     = Split('''
posix_file.c
posix_clock.c
posix_thread.c
posix_socket.c
''')
CPPPATH = [cwd]

group = DefineGroup('iwasm_common_posix', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
