#
# Copyright (c) 2021, RT-Thread Development Team
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#


from building import *
import os

cwd     = GetCurrentDir()

src = Split('''
''')

def is_as_pthread(src):
    filters = ["rtt_thread.c"]
    for filter in filters:
        if filter in src:
            return False
    return True

def addSrcFiles(arr, path):
    for f in os.listdir(path):
        fpath = os.path.join(path, f);
        if os.path.isfile(fpath):
            ext = os.path.splitext(fpath)[-1]
            if ext == '.c' or ext == '.cpp':
                arr += [fpath]
        elif os.path.isdir(fpath):
            addSrcFiles(arr, fpath)

addSrcFiles(src, cwd);
if GetDepend('RT_USING_PTHREADS'):
    src = list(filter(is_as_pthread, src))

CPPPATH = [cwd, cwd+'/../include']

group = DefineGroup('iwasm_platform_core', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
